// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_BROWSER']!,
    appId: '1:1007068661118:web:20831cfaf87f8d16efdf2f',
    messagingSenderId: '1007068661118',
    projectId: 'flutter-line',
    authDomain: 'flutter-line.firebaseapp.com',
    storageBucket: 'flutter-line.firebasestorage.app',
    measurementId: 'G-R0Q5Z1CVGQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:1007068661118:android:396e852cefdbbf40efdf2f',
    messagingSenderId: '1007068661118',
    projectId: 'flutter-line',
    storageBucket: 'flutter-line.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:1007068661118:ios:3c56b7e05cd640d4efdf2f',
    messagingSenderId: '1007068661118',
    projectId: 'flutter-line',
    storageBucket: 'flutter-line.firebasestorage.app',
    iosBundleId: 'com.example.line',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:1007068661118:ios:3c56b7e05cd640d4efdf2f',
    messagingSenderId: '1007068661118',
    projectId: 'flutter-line',
    storageBucket: 'flutter-line.firebasestorage.app',
    iosBundleId: 'com.example.line',
  );
}
